import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js",
    template: "%s | kunal page",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "greenyellow", padding: "3rem" }}>
          <p>header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "lightskyblue", padding: "3rem" }}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
